apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  chart:
    spec:
      chart: alloy
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    alloy:
      configMap:
        content: |
          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "logs" {
            targets = discovery.kubernetes.pods.targets
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "replace"
              target_label = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              action = "replace"
              target_label = "pod"
            }
          }

          loki.source.kubernetes "logs" {
            targets    = discovery.relabel.logs.output
            forward_to = [loki.write.grafana_loki.receiver]
          }

          loki.write "grafana_loki" {
            endpoint {
              url = "http://loki:3100/loki/api/v1/push"
            }
          }