apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/config-management-plugin: helm
apiVersion: argoproj.io/v1alpha1
kind: Repository
metadata:
  name: grafana-charts
spec:
  type: helm
  url: https://grafana.github.io/helm-charts