apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api
  namespace: default
  labels:
    app: telemetry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
    spec:
      containers:
        - name: telemetry-api
          image: ghcr.io/kamilekbeznosa/iaacprojects:0702f90
          ports:
            - containerPort: 8080
              name: http-web
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi