apiVersion: v1
kind: Service
metadata:
  name: telemetry-api-svc
  namespace: default
  labels:
    app: telemetry-api
spec:
  selector:
    app: telemetry-api
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
  type: ClusterIP