apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telemetry-api-monitor
  namespace: monitoring
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: telemetry-api
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http-web
      path: /metrics
      interval: 15s