apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: k6
        image: loadimpact/k6
        command: ["k6", "run", "-"]
        args:
          - |
            import http from 'k6/http';
            import { sleep } from 'k6';
            export const options = { vus: 10, duration: '30m' };
            export default function () {
              http.get('http://telemetry-api-svc.default.svc.cluster.local');
              sleep(0.5);
            }
      restartPolicy: OnFailure