apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: k6
        image: loadimpact/k6
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo 'import http from "k6/http";
            import { sleep } from "k6";
            export const options = { vus: 10, duration: "30m" };
            export default function () {
              http.get("http://telemetry-api-svc.default.svc.cluster.local");
              sleep(0.5);
            }' > load-test.js && k6 run load-test.js
      restartPolicy: OnFailure